# Generated by Django 4.2 on 2023-04-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dic",
            fields=[
                ("word_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("word_Nihon", models.CharField(max_length=250)),
                ("Word_Meaning_Eng", models.CharField(max_length=250)),
                ("Word_Meaning_Eng2", models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
