# Generated by Django 4.2 on 2023-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0002_dic_delete_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="dic",
            name="Word_Meaning_Eng3",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="dic",
            name="word_Nihon_Similar",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="dic",
            name="Word_Meaning_Eng2",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
