# Generated by Django 4.2 on 2023-04-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0003_dic_word_meaning_eng3_dic_word_nihon_similar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dic",
            name="word_Kanji",
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
