# Generated by Django 4.1 on 2023-05-16 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_dic_word_kanji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dic',
            name='Word_Meaning_Eng2',
        ),
        migrations.RemoveField(
            model_name='dic',
            name='Word_Meaning_Eng3',
        ),
    ]
