# Generated by Django 4.1 on 2023-05-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_remove_dic_word_meaning_eng2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dic',
            name='word_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
